export const NotificationNames = {
  STATE_CHANGE: 'STATE_CHANGE',
  DATA_CHANGE: 'DATA_CHANGE',
  RENDER: 'RENDER',
  CLICK: 'CLICK',
  STARTUP: 'STARTUP',
  STARTUP_COMPLETE: 'STARTUP_COMPLETE'
};

export const EventNames = {
  CLICK_GLOBAL_COUNT: 'CLICK_GLOBAL_COUNT',
  SUBVIEW_GLOBAL_COUNT: 'SUBVIEW_GLOBAL_COUNT',
  SUBVIEW_LOCAL_COUNT: 'SUBVIEW_LOCAL_COUNT',
};
