export const NotificationNames = {
  STATE_CHANGE: 'STATE_CHANGE',
  RENDER: 'RENDER',
  CLICK: 'CLICK',
  STARTUP: 'STARTUP'
};

export const EventNames = {
  SUBVIEW_GLOBAL_COUNT: 'SUBVIEW_GLOBAL_COUNT',
  SUBVIEW_LOCAL_COUNT: 'SUBVIEW_LOCAL_COUNT'
};
